<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="quilt.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="quilt.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.9.0-ci-20250329.14150108340" />
  </ItemGroup>

</Project>
